### ISSUE TITLE
Got err in building docker

### ISSUE THREAD

**Issue by loginyourheart** [owtf/owtf-docker#34]
i jsut run command docker build -t owtf-dev .

and i got an Err as follows:
-------------------------------------------------------

Sending build context to Docker daemon  123.4kB
Step 1/26 : FROM kalilinux/kali-linux-docker
 ---> b8fe82f15421
Step 2/26 : MAINTAINER @viyatb viyat.bhalodia@owasp.org, @alexandrasandulescu alecsandra.sandulescu@gmail.com
 ---> Using cache
 ---> 584a88ed2a37
Step 3/26 : RUN wget -q -O - archive.kali.org/archive-key.asc | apt-key add
 ---> Running in 8145b8252775
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c wget -q -O - archive.kali.org/archive-key.asc | apt-key add' returned a non-zero code: 255
--------------------------------------------------------
How could i fix it?thx
--------------------------------------------------------
env :
Docker version 17.09.1-ce, build 19e2cf6

Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty

Linux  3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by viyatb** [comment]
@loginyourheart please update your Kali image, `docker pull kalilinux/kali-linux-docker`

**Comment by loginyourheart** [comment]
thank you for your reply
it seems already updated to the latest version ， and i still got that error ：）
-----------------------
$ docker pull kalilinux/kali-linux-docker

Using default tag: latest
latest: Pulling from kalilinux/kali-linux-docker
Digest: sha256:afdb5edb5732016fc5aea02ab1f1a9083c769016c2a0074887e83e057fa0f294
Status: Image is up to date for kalilinux/kali-linux-docker:latest

----
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

The command '/bin/sh -c wget -q -O - archive.kali.org/archive-key.asc | apt-key add' returned a non-zero code: 255

---------

**Comment by anthonyvdotbe** [comment]
I have the same issue. After adding
`RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y gnupg`
in front of the failing line, it doesn't give that error anymore, but other errors occur:
- in optional_tools.sh, there's a package "waffit" which apt-get is unable to find
- in Dockerfile, `RUN mkdir owtf/tools/restricted` fails
- in Dockerfile, `RUN python owtf/install/install.py` fails

This is on Windows 10 (1709) with Docker version 18.03.1-ce, build 9ee9f40

**Comment by kj0317** [comment]
Hi, I'm attempting to install this as well and I'm getting the same error as anthonyvdotbe. This is from Kali Linux running docker version 18.03.1-ce.

**Comment by viyatb** [comment]
Fixed in https://github.com/owtf/owtf-docker/commit/1d1f8ca0c7887857342fb1f5937ecc3281758cea.
